name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/

      - name: Run tests
        run: ctest --test-dir build